"use client";

import { useParams } from "next/navigation";
import { Container } from "@/components/ui/container";

const topicContent: Record<
  string,
  { title: string; description: string; sections: { heading: string; body: string }[] }
> = {
  "ebv-ms": {
    title: "EBV & Multiple Sclerosis",
    description:
      "Epstein-Barr virus is present in nearly 100% of MS patients. The question isn't whether EBV is involved, but how.",
    sections: [
      {
        heading: "Latent disruption, not reactivation",
        body: "EBV latent proteins (EBNA1, LMP1) disrupt iron-buffering systems in oligodendrocytes. LMP1 activates NF-kB, which downregulates ferroportin, trapping iron inside cells. EBNA1 mimics host proteins involved in iron regulation.",
      },
      {
        heading: "Iron rim lesions",
        body: "Iron rim lesions in MS mark where iron-buffering systems have collapsed. These lesions expand slowly, driven by iron-catalyzed oxidative damage to surrounding oligodendrocytes. This is the ferroptosis cascade in action.",
      },
      {
        heading: "Why antivirals don't help established MS",
        body: "Once structural damage is done, eliminating the virus doesn't reverse it. The iron distribution is already disrupted. Demyelinated axons are already exposed. This matches the FELINE prediction that prevention differs from treatment.",
      },
    ],
  },
  covid: {
    title: "SARS-CoV-2 & Neurodegeneration",
    description:
      "SARS-CoV-2 compresses decades of neurodegenerative decline into months by directly attacking the neurovascular layer.",
    sections: [
      {
        heading: "Pericyte infection via CD147",
        body: "SARS-CoV-2 infects brain pericytes through CD147 (basigin), the same receptor used for erythrocyte invasion by malaria parasites. Pericyte death breaches the blood-brain barrier, allowing uncontrolled iron entry into brain parenchyma.",
      },
      {
        heading: "Rapid biomarker development",
        body: "Long COVID patients develop elevated NfL (neurofilament light chain), GFAP, and phospho-tau within months of infection. These are the same biomarkers seen in Alzheimer's and Parkinson's, appearing at an accelerated rate.",
      },
      {
        heading: "Multi-layer assault",
        body: "SARS-CoV-2 doesn't just breach the barrier. It also triggers hepcidin elevation (trapping iron in cells), disrupts glymphatic flow (reducing iron export), and depletes glutathione (compromising antioxidant defense). Multiple layers fail simultaneously.",
      },
    ],
  },
  "latent-proteins": {
    title: "Latent Viral Proteins",
    description:
      "The mechanism that connects viral infection to neurodegeneration doesn't require active replication.",
    sections: [
      {
        heading: "Iron-buffering sabotage",
        body: "Latent viral proteins disrupt the very proteins the brain uses to buffer iron. Tau, alpha-synuclein, and ferritin all have iron-binding roles. Viral interference with these proteins releases sequestered iron into the cytoplasm.",
      },
      {
        heading: "Antioxidant depletion",
        body: "Latent infection chronically depletes glutathione and NAD+, the substrates that GPX4 and SIRT3 require. Without these defenses, cells cannot neutralize the lipid peroxides generated by free iron.",
      },
      {
        heading: "The decades-long fuse",
        body: "This explains the long latency between infection and disease. Viral proteins slowly erode iron-buffering capacity over years. Disease appears when enough defense layers have been degraded that the system can no longer compensate.",
      },
    ],
  },
};

export default function ViralTopicPage() {
  const { topic } = useParams<{ topic: string }>();
  const data = topicContent[topic];

  if (!data) {
    return (
      <Container width="reading" className="py-12">
        <h1 className="text-2xl font-bold text-white">Topic not found</h1>
        <p className="mt-2 text-gray-400">Unknown topic: {topic}</p>
      </Container>
    );
  }

  return (
    <Container width="reading" className="py-12">
      <h1 className="text-3xl font-bold text-white sm:text-4xl mb-4">
        {data.title}
      </h1>
      <p className="text-lg text-gray-400 leading-relaxed mb-10">
        {data.description}
      </p>

      <div className="space-y-8">
        {data.sections.map((section) => (
          <section key={section.heading} className="glass-card p-6">
            <h2 className="text-lg font-bold text-white mb-3">
              {section.heading}
            </h2>
            <p className="text-gray-300 leading-relaxed">{section.body}</p>
          </section>
        ))}
      </div>
    </Container>
  );
}
