// Iron-Dependent Viral Reactivation — structured data for /explore/viral/iron-reactivation

import type { MechanismStep } from "./iron-cascades";

/* ── Interfaces ─────────────────────────────────────────────────────── */

export interface ViralMechanismSection {
  id: string;
  kicker: string;
  title: string;
  subtitle: string;
  mechanismSteps: MechanismStep[];
}

export interface ExportFailureRow {
  exportFailure: string;
  ironConsequence: string;
  reactivationEffect: string;
}

export interface AgeWindowRow {
  phenomenon: string;
  ageThreshold: string;
  references: string;
}

export interface CrossVirusRow {
  virus: string;
  latencySite: string;
  disease: string;
  targetTissue: string;
  ironLink: string;
}

export interface EpidemiologicalStudy {
  study: string;
  journal: string;
  year: number;
  finding: string;
  detail?: string;
}

export interface TestablePrediction {
  number: number;
  prediction: string;
  rationale: string;
}

export interface AmplificationStep {
  id: string;
  label: string;
}

/* ── Hero ────────────────────────────────────────────────────────────── */

export const viralReactivationHero = {
  kicker: "Viral Mechanisms",
  title: "Viral reactivation is iron-dependent",
  subtitle:
    "Three decades of research treated viral reactivation, tau aggregation, and iron accumulation as independent disease loops. The iron-dependent enzymology of herpesvirus latency collapses them into one master loop with two amplifiers.",
};

/* ── Latency Background ─────────────────────────────────────────────── */

export const latencyBackground = {
  title: "How latency works",
  points: [
    "During latency, herpesvirus lytic genes are silenced by repressive histone marks: H3K9me2/me3 and H3K27me3 coat lytic promoters.",
    "Only the LAT (latency-associated transcript) region remains active. All lytic genes are locked behind heterochromatin.",
    "Reactivation requires enzymatic removal of these repressive marks. The enzymes that do this are the gatekeepers of reactivation.",
    "The critical insight: those gatekeeper enzymes require iron as an obligate cofactor.",
  ],
};

/* ── Four Mechanisms ─────────────────────────────────────────────────── */

export const jmjcMechanism: ViralMechanismSection = {
  id: "jmjc",
  kicker: "Mechanism 1",
  title: "JmjC demethylases are iron-dependent",
  subtitle:
    "The enzymes that unlock viral genomes require Fe\u00B2\u207A as an obligate cofactor. Rising intracellular iron directly increases their activity.",
  mechanismSteps: [
    {
      step: 1,
      title: "JmjC enzymes require Fe\u00B2\u207A + \u03B1-ketoglutarate",
      body: "Jumonji C domain demethylases (JMJD2/KDM4, JMJD3/KDM6B, UTX/KDM6A, LSD1/KDM1A) catalyze the removal of methyl groups from histones. They are Fe\u00B2\u207A and \u03B1-ketoglutarate-dependent dioxygenases. Without iron, they cannot function.",
      keyPaper: "Hong et al. 2007, PNAS",
      detail:
        "The Jumonji C domain was first identified as a histone demethylase domain in 2006-2007. The iron requirement is absolute, not modulatory.",
    },
    {
      step: 2,
      title: "LIP fluctuations control JmjC activity",
      body: "The neuronal labile iron pool (LIP) is normally 0.2\u20131 \u03BCM. JmjC enzymes have Km values in the same range, making their activity exquisitely sensitive to LIP fluctuations. Small increases in intracellular iron translate directly to enhanced demethylase activity.",
      detail:
        "This Km-LIP overlap means JmjC demethylases act as molecular iron sensors. They don't need large iron shifts to change behavior.",
    },
    {
      step: 3,
      title: "Iron accumulation \u2192 lytic gene derepression",
      body: "Rising LIP \u2192 enhanced JmjC activity \u2192 removal of H3K9me3 and H3K27me3 from viral lytic promoters \u2192 transcription of immediate-early genes \u2192 reactivation cascade. Liang et al. showed that inhibiting these demethylases blocks HSV-1 reactivation entirely.",
      keyPaper: "Liang et al. 2009, Nature Medicine; Liang et al. 2013, Science Translational Medicine",
      quote:
        "Inhibition of LSD1 by tranylcypromine prevented HSV reactivation from latency in mice",
    },
  ],
};

export const gshMechanism: ViralMechanismSection = {
  id: "gsh",
  kicker: "Mechanism 2",
  title: "GSH depletion triggers reactivation",
  subtitle:
    "Iron-driven Fenton chemistry depletes the same antioxidant buffer that keeps viruses latent, linking reactivation to the prodromal stage of ferroptosis.",
  mechanismSteps: [
    {
      step: 1,
      title: "Iron \u2192 Fenton reaction \u2192 GSH consumption",
      body: "Fe\u00B2\u207A + H\u2082O\u2082 \u2192 Fe\u00B3\u207A + OH\u2022 + OH\u207B. The hydroxyl radicals generated by Fenton chemistry are neutralized by glutathione (GSH), consuming the cellular antioxidant reserve. Rising iron accelerates GSH depletion.",
      detail:
        "GSH is the primary intracellular antioxidant. Its depletion precedes ferroptosis by hours to days, creating a window of vulnerability.",
    },
    {
      step: 2,
      title: "GSH depletion activates viral lytic switch",
      body: "When GSH drops, H\u2082O\u2082 accumulates and activates viral lytic switch proteins. For KSHV, this means RTA activation. For HSV-1, the likely pathway involves ICP0 and VP16. Ye et al. showed that GSH depletion alone is sufficient to reactivate KSHV from latency.",
      keyPaper: "Ye et al. 2011, Journal of Virology",
    },
    {
      step: 3,
      title: "Reactivation at the prodromal stage of ferroptosis",
      body: "The same GSH depletion that triggers viral reactivation also primes the cell for ferroptosis. The virus reactivates at the prodromal stage of cell death, not after. This creates a lethal synergy: the virus escapes just as the host cell begins to die, releasing both viral particles and stored iron into the local environment.",
      keyPaper: "Sebastiano & Bhatt 2016, Current Zoology",
      detail:
        "This timing is not coincidental. It represents evolutionary optimization: the virus senses impending cell death via the same redox signal and initiates escape.",
    },
  ],
};

export const grMechanism: ViralMechanismSection = {
  id: "gr",
  kicker: "Mechanism 3",
  title: "Glucocorticoid receptor activation",
  subtitle:
    "Iron-driven oxidative stress activates the glucocorticoid receptor without cortisol, providing a tonic reactivation signal and suppressing local immunity.",
  mechanismSteps: [
    {
      step: 1,
      title: "Ligand-independent GR activation via S134 phosphorylation",
      body: "The glucocorticoid receptor (GR) can be activated without its ligand (cortisol) through phosphorylation at serine 134. Oxidative stress, including iron-driven ROS, triggers this phosphorylation. The result is constitutive GR activation in iron-loaded cells.",
      keyPaper: "Jones 2023, Current Clinical Microbiology Reports",
    },
    {
      step: 2,
      title: "Chronic Fenton chemistry \u2192 tonic reactivation signal",
      body: "Iron-driven chronic Fenton chemistry produces sustained oxidative stress \u2192 constitutive GR activation \u2192 continuous low-level reactivation pressure on latent herpesviruses. GR activation also suppresses local immune surveillance, reducing the immune system's ability to contain reactivation events.",
      keyPaper: "Glaser & Kiecolt-Glaser 2005, Nature Reviews Immunology",
      detail:
        "This explains why psychological stress (cortisol-mediated) and iron accumulation (ROS-mediated) both trigger reactivation through the same receptor.",
    },
  ],
};

export const heterochromatinMechanism: ViralMechanismSection = {
  id: "heterochromatin",
  kicker: "Mechanism 4",
  title: "Heterochromatin erosion",
  subtitle:
    "Iron-driven ROS damage the proteins that maintain viral gene silencing, producing the low-level leaky reactivation pattern seen clinically as asymptomatic shedding.",
  mechanismSteps: [
    {
      step: 1,
      title: "ROS carbonylation of heterochromatin proteins",
      body: "Iron-driven ROS cause carbonylation (irreversible oxidative damage) of key heterochromatin maintenance proteins: HP1, Polycomb group proteins, HDACs, and the ATRX/DAXX complex. These proteins are required to maintain the repressive chromatin state on viral lytic genes.",
      keyPaper: "Mathew et al. 2010, Journal of Virology",
    },
    {
      step: 2,
      title: "Leaky reactivation \u2192 asymptomatic shedding",
      body: "Unlike the all-or-nothing reactivation from Mechanisms 1-3, heterochromatin erosion produces low-level, stochastic leaking of lytic gene expression. This pattern is consistent with asymptomatic viral shedding: subclinical reactivation events that don't produce symptoms but do trigger immune responses, including hepcidin surges that trap more iron.",
      detail:
        "This mechanism operates continuously in iron-loaded tissue and may be the dominant mode of viral reactivation in the aging brain, where frank symptomatic reactivation is rare but subclinical shedding is common.",
    },
  ],
};

/* ── Amplification Spiral ────────────────────────────────────────────── */

export const amplificationSpiral: AmplificationStep[] = [
  { id: "iron", label: "Iron accumulation" },
  { id: "jmjc", label: "JmjC activation" },
  { id: "reactivation", label: "Viral reactivation" },
  { id: "hepcidin", label: "Hepcidin surge" },
  { id: "fpn", label: "Ferroportin degradation" },
  { id: "trapping", label: "More iron trapped" },
];

export const exportFailureTable: ExportFailureRow[] = [
  {
    exportFailure: "Tau aggregation \u2192 ferroportin loss",
    ironConsequence:
      "Gradual LIP rise over months to years as tau loses iron-buffering capacity",
    reactivationEffect:
      "Slow ramp of JmjC activity; increasing heterochromatin erosion; rising asymptomatic shedding",
  },
  {
    exportFailure: "Hepcidin surge (infection/inflammation)",
    ironConsequence:
      "Acute ferroportin degradation \u2192 sudden LIP spike within hours",
    reactivationEffect:
      "Rapid JmjC activation + GSH depletion; threshold-crossing for full lytic reactivation",
  },
  {
    exportFailure: "Combined: tau + hepcidin",
    ironConsequence:
      "Catastrophic iron loading: baseline already elevated, acute spike pushes past threshold",
    reactivationEffect:
      "All 4 mechanisms activate simultaneously; full lytic burst with maximum tissue damage",
  },
  {
    exportFailure: "OL ferroptosis \u2192 iron release",
    ironConsequence:
      "Oligodendrocyte death releases 3.05 mM stored iron into local environment",
    reactivationEffect:
      "Iron floods neighboring neurons and glia; activates latent virus in adjacent cells",
  },
];

/* ── Age Window ──────────────────────────────────────────────────────── */

export const ageWindowTable: AgeWindowRow[] = [
  {
    phenomenon: "Shingles (VZV reactivation)",
    ageThreshold: "50\u201360 years",
    references: "CDC epidemiology; Shingrix recommended age 50+",
  },
  {
    phenomenon: "Alzheimer's clinical onset",
    ageThreshold: "55\u201365 years",
    references: "Braak staging; clinical trial entry criteria",
  },
  {
    phenomenon: "Parkinson's motor symptoms",
    ageThreshold: "55\u201365 years",
    references: "de Lau & Breteler 2006, Lancet Neurology",
  },
  {
    phenomenon: "Basal ganglia iron plateau",
    ageThreshold: "50\u201360 years",
    references: "Hallgren & Sourander 1958; Aquino et al. 2009, Radiology",
  },
  {
    phenomenon: "Substantia nigra iron peak",
    ageThreshold: "50\u201370 years",
    references: "Zecca et al. 2004, Nature Reviews Neuroscience",
  },
];

export const ageWindowExplanation =
  "Under FELINES, the same iron threshold simultaneously unlocks viral genomes (via JmjC activation), provides tau with its aggregation cofactor, and overwhelms GPX4 capacity. The basal ganglia are the most iron-rich brain structures AND the primary VZV vasculopathy targets AND the primary site of PD degeneration. This convergence is not coincidental.";

/* ── Epidemiological Evidence ────────────────────────────────────────── */

export const epidemiologicalStudies: EpidemiologicalStudy[] = [
  {
    study: "Eyting et al. 2025",
    journal: "Nature",
    year: 2025,
    finding:
      "Shingles vaccination reduced dementia incidence by 20% in a Welsh natural experiment",
    detail:
      "Wales introduced shingles vaccination on September 1, 2013 with a sharp age cutoff (born before vs. after Sept 2, 1933). People just young enough to qualify had 20% less dementia over the next 7 years. The sharp eligibility boundary creates a natural experiment that controls for confounders.",
  },
  {
    study: "Geldsetzer et al. 2025",
    journal: "Cell",
    year: 2025,
    finding:
      "Extended analysis confirmed dementia reduction and showed lower MCI and dementia mortality",
    detail:
      "Replicated the Eyting finding with additional endpoints: reduced mild cognitive impairment (MCI) and lower dementia-specific mortality in the vaccinated cohort.",
  },
  {
    study: "Taquet et al. 2024",
    journal: "Nature Medicine",
    year: 2024,
    finding:
      "Recombinant zoster vaccine associated with 17% more diagnosis-free time (164 days)",
    detail:
      "Comparison of recombinant (Shingrix) vs. live (Zostavax) vaccines showed the more effective vaccine produced greater dementia protection.",
  },
  {
    study: "IDWeek 2025 (conference)",
    journal: "IDWeek 2025",
    year: 2025,
    finding: "Shingles vaccination associated with 50% lower vascular dementia risk",
    detail:
      "Vascular dementia showed the largest effect size, consistent with VZV vasculopathy as a mechanism.",
  },
  {
    study: "Bae et al. 2025",
    journal: "Nature Medicine",
    year: 2025,
    finding:
      "100M-person EHR study: recurrent herpes zoster increased dementia risk; vaccination reduced it",
    detail:
      "The largest electronic health record study to date. Recurrent zoster episodes correlated with higher dementia incidence. Vaccination was protective in a dose-dependent manner.",
  },
];

export const cairnsCascade = {
  title: "The two-stage cascade",
  study: "Cairns et al. 2022, Journal of Alzheimer's Disease",
  finding:
    "VZV triggers HSV-1 reactivation in latently infected neural stem cells, producing AD-like changes (A\u03B2, pTau). VZV alone produces neither.",
  detail:
    "This two-stage cascade (VZV \u2192 HSV-1 \u2192 AD pathology) fits the FELINES model: iron \u2192 VZV reactivation \u2192 hepcidin surge \u2192 more iron trapped \u2192 HSV-1 reactivation \u2192 neurodegeneration.",
  felineInterpretation:
    "Preventing subclinical VZV reactivations (via vaccination) prevents hepcidin surges, which prevents iron trapping, which prevents HSV-1 reactivation. The vaccine effect is an iron-export protection effect.",
};

/* ── Cross-Virus Comparison ──────────────────────────────────────────── */

export const crossVirusTable: CrossVirusRow[] = [
  {
    virus: "HSV-1",
    latencySite: "Trigeminal ganglia neurons",
    disease: "Alzheimer's disease",
    targetTissue: "Temporal lobe, hippocampus",
    ironLink:
      "JmjC demethylases require Fe\u00B2\u207A; hippocampal iron rises with age",
  },
  {
    virus: "VZV",
    latencySite: "Dorsal root ganglia neurons",
    disease: "Shingles, VZV vasculopathy",
    targetTissue: "Sensory nerves, cerebral vessels",
    ironLink:
      "Basal ganglia iron-rich regions = VZV vasculopathy targets; vaccine reduces dementia 20%",
  },
  {
    virus: "EBV",
    latencySite: "Memory B cells",
    disease: "Multiple sclerosis",
    targetTissue: "CNS white matter",
    ironLink:
      "Iron rim lesions in MS; EBV latent proteins disrupt iron buffering in oligodendrocytes",
  },
  {
    virus: "CMV",
    latencySite: "Myeloid progenitors",
    disease: "Immune aging, vascular disease",
    targetTissue: "Endothelium, immune cells",
    ironLink:
      "CMV seropositivity correlates with higher ferritin and inflammatory iron sequestration",
  },
  {
    virus: "HHV-6A",
    latencySite: "Astrocytes, oligodendrocytes",
    disease: "Alzheimer's disease, MS",
    targetTissue: "Temporal lobe, white matter",
    ironLink:
      "Readhead et al. 2018: HHV-6A enriched in AD brains; astrocytes are iron-regulatory hubs",
  },
  {
    virus: "HHV-7",
    latencySite: "T cells, salivary glands",
    disease: "Pityriasis rosea, immune modulation",
    targetTissue: "Skin, immune system",
    ironLink:
      "Can trigger HHV-6 reactivation (cascade effect); iron-dependent reactivation likely shared",
  },
  {
    virus: "HIV",
    latencySite: "CD4+ T cells, macrophages",
    disease: "AIDS, HAND",
    targetTissue: "Immune system, basal ganglia",
    ironLink:
      "HIV Tat protein disrupts iron homeostasis; HAND targets iron-rich basal ganglia",
  },
  {
    virus: "JC virus",
    latencySite: "Kidney, bone marrow",
    disease: "PML",
    targetTissue: "Oligodendrocytes",
    ironLink:
      "JC virus targets iron-rich oligodendrocytes; PML = pure demyelination",
  },
];

/* ── Testable Predictions ────────────────────────────────────────────── */

export const testablePredictions: TestablePrediction[] = [
  {
    number: 1,
    prediction:
      "JmjC demethylase inhibitors will block herpesvirus reactivation in iron-loaded neuronal cultures in a dose-dependent manner",
    rationale:
      "If iron-driven JmjC activity is the primary reactivation trigger, then inhibiting these enzymes should prevent reactivation even when iron is elevated. Liang et al. showed this for LSD1; the prediction extends it to JMJD2/KDM4 family members.",
  },
  {
    number: 2,
    prediction:
      "Brain regions with the highest iron concentrations will show the highest rates of herpesvirus reactivation and viral DNA load",
    rationale:
      "The iron-dependence model predicts spatial correlation between iron deposition and viral activity. The basal ganglia (highest iron) should show more viral reactivation than cortical regions (lower iron).",
  },
  {
    number: 3,
    prediction:
      "Deferiprone (brain-penetrant iron chelator) will reduce herpesvirus reactivation frequency in animal models",
    rationale:
      "If LIP drives reactivation via JmjC activation, then reducing LIP with a chelator should reduce reactivation. This is testable in HSV-1 latency mouse models.",
  },
  {
    number: 4,
    prediction:
      "Shingles vaccine recipients will show slower rates of brain iron accumulation on QSM-MRI compared to unvaccinated controls",
    rationale:
      "If VZV reactivation drives hepcidin surges that trap iron, preventing reactivation should slow iron accumulation. This is measurable with quantitative susceptibility mapping.",
  },
  {
    number: 5,
    prediction:
      "Serum hepcidin will spike within 24\u201348 hours of herpesvirus reactivation events, even subclinical ones",
    rationale:
      "Reactivation triggers innate immune activation \u2192 IL-6 \u2192 hepcidin. If subclinical reactivations produce measurable hepcidin spikes, this confirms the iron-trapping mechanism.",
  },
  {
    number: 6,
    prediction:
      "Post-mortem AD brains with high HSV-1 viral load will show higher iron concentrations in the same regions, independent of amyloid plaque density",
    rationale:
      "The iron model predicts regional co-localization of iron and viral load. If iron drives reactivation (not vice versa), iron elevation should precede or match viral load, not simply correlate with amyloid.",
  },
];
